In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')
chipo.head()

In [ ]:
chipo.shape[0]

In [ ]:
chipo.shape[1]

In [ ]:
chipo.info()

In [ ]:
chipo.columns

In [ ]:
chipo.index

## Boolean Index(참인것들만 필터링)

In [ ]:
chipo.columns

In [1]:
import pandas as pd

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# DataFrame
df = pd.DataFrame({
    "value": np.random.randn(4622).cumsum()
}, index=pd.RangeIndex(0, 4622))

x = df.index.values
y = df["value"].values

# 추세선
z = np.polyfit(x, y, 1)
p = np.poly1d(z)

plt.figure(figsize=(12, 5))
plt.plot(df.index, df["value"], label="Data")
plt.plot(df.index, p(x), "r--", label="Trend")

plt.legend()
plt.show()

In [ ]:
df1 = pd.DataFrame({
    '병국': [1,2,3,4,5],
    '소라': [10,20,30,40,50]
})
df1
df1[df1['소라']>30]
data = (df1['병국']>3) & (df1['소라']<50)
df1[data]

In [ ]:
df2=pd.DataFrame({
    'a': [10,4,6,4,1],
    'b': [20,5,2,4,3],
    'c': [30,7,4,5,7],
    'd': ["홍길동","김말자","김개똥","김유라","신소라"]
})
result = df2[['a','b','d']]
result[result['d'].str.contains("김")]

In [ ]:
data = pd.DataFrame({
    'a':[1,2,3],
    'b':[4,5,6],
    'c':['a','a','b']
})
data
# data.groupby('c').sum()
data.groupby('c').mean()

In [ ]:
def f1(i):
    return str(i.sum())+"사랑합니다"

In [ ]:
def f2(i):
    return str(i.mean())+"미안합니다"

In [ ]:
data.groupby('c').agg([sum, 'mean', f1, f2])

<img src="image/img.JPG"/>

In [ ]:
c = chipo.groupby('item_name')
c = c.sum()
c = c.sort_values(['quantity'], ascending = False)
c.head()

In [ ]:
data = pd.DataFrame({
    "Col1":["A", "B", "C", "C", "B", "B", "A"],
    "Col2": [1, 2, 3, 4, 2, 5, 3]
})
data

In [ ]:
d=np.array([1,2,3,4,5])
d[1:-2] # [  )  , 좌측은 포함(폐구간), 우측은 포함하지 않음(개구간)

In [ ]:
str2 = '$3.45'
float(str2[1:-2])

In [ ]:
cnt=0
def f_control(i):
    cnt+=1
    print('i:',i,', cnt:', cnt)

In [ ]:
# 성이 '김'을 가진 사람의 총합구하기 2.45+7.45 = 9.9
dd=pd.DataFrame({
    'd':['$3.15$', '$2.45%','$7.45%' ,'$8.45%' ,'$9.451%' ],
    'f':['홍길동','김말자','김순애','유라','오이']
})
df5= (dd)
df5

In [ ]:
data5 = df5[df5['f'].str.contains('김')]
# df5[df5['f'].str.contains("김")['d'].apply(slice).sum()
data6 = data5['d'].str[1:-1]
sum1=0
for i in data6:
    sum1+=float(i)
sum1

In [ ]:
data.groupby('Col1').apply(sum, f_control)

In [ ]:
dollarizer = lambda x: float(x[1:-2])
chipo.item_price = chipo.item_price.apply(dollarizer)
chipo

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep = '\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [6]:
## 10달러 이상인 제품은 얼마나 많은 상품이 있는지
## 각각의 항목의 가격 column은 제품가격과 수량을 곱한 결과이다
chipo.loc[(chipo["choice_description"]=='[Diet Coke]') & (chipo["item_name"]=='Canned Soda')].tail()

,order_id,quantity,item_name,choice_description,item_price,product_price
2544,1009,1,Canned Soda,[Diet Coke],1.09,1.09
2850,1132,1,Canned Soda,[Diet Coke],1.09,1.09
3592,1440,2,Canned Soda,[Diet Coke],2.18,1.09
3793,1518,1,Canned Soda,[Diet Coke],1.09,1.09
4008,1604,1,Canned Soda,[Diet Coke],1.09,1.09

In [4]:
chipo['item_price'] = chipo['item_price'].str.replace("$",'',regex=False).astype(float)
chipo['product_price'] = chipo['item_price']/chipo['quantity']
chipo

,order_id,quantity,item_name,choice_description,item_price,product_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [29]:
df7 = pd.DataFrame({
    'item':["가방", "책", "노트", "수박"],
    'price':['$500', '$50', '$100', '$1000'],
    'quantity':['2%', '3%', '4%', '1%'],
    'name':["김말자", "김개똥", "김유라", "신소라"]
})
df7

  item  price quantity name
0   가방   $500       2%  김말자
1    책    $50       3%  김개똥
2   노트   $100       4%  김유라
3   수박  $1000       1%  신소라

In [31]:
data7 = df7[df7['name'].str.contains('김')]
price = data7['price'].str[1:].astype(float)
quantity = data7['quantity'].str[0:-1].astype(int)
data7['price'] = price*quantity
data7[['name','item','price']]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3704\4125637825.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data7['price'] = price*quantity

  name item   price
0  김말자   가방  1000.0
1  김개똥    책   150.0
2  김유라   노트   400.0

In [38]:
import pandas as pd
import numpy as np

In [33]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv',keep_default_na=False)
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [34]:
# 어떤 continent가 평균이상 맥주를 마시는가
drinks.groupby('continent').beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
NA    145.434783
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

In [35]:
drinks.groupby('continent').wine_servings.describe()  #25%	50%	75% => percetitle

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
NA          23.0   24.521739  28.266378  1.0   5.0   11.0   34.00  100.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

<img src=image/표준편차.JPG/>

In [45]:
drink_af_continent = drinks[drinks['continent']=='AF']
data_drink_af_continent = drink_af_continent.wine_servings
data_drink_af_continent_sum = data_drink_af_continent.sum()
data_drink_af_continent_cnt = data_drink_af_continent.count()
data_drink_af_continent_mean = data_drink_af_continent_sum/data_drink_af_continent_cnt
data_drink_af_continent_mean - data_drink_af_continent.mean() < 0.0001

np.True_

In [46]:
data_drink_af_continent_std = data_drink_af_continent.std()
data_drink_af_continent_std

38.8464189733584

In [51]:
denominator = data_drink_af_continent - data_drink_af_continent_mean
result = 0
for i in data_drink_af_continent:
    rr = i - data_drink_af_continent_mean
    result += (rr*rr)/data_drink_af_continent_cnt
np.sqrt(result)

np.float64(38.47819816094648)

In [52]:
drinks.groupby('continent').mean(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
NA,145.434783,165.739130,24.521739,5.995652
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

In [53]:
drinks.groupby('continent').median(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
NA,143.0,137.0,11.0,6.30
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

In [54]:
np.array([1,2,1000]).mean()

np.float64(334.3333333333333)

In [56]:
pd.DataFrame({'a':[1,2,1000]}).median()

a    2.0
dtype: float64